from turtle import width
import streamlit as st
import pandas as pd
from PIL import Image, ImageDraw

# -----------------------------------------------------------
image_path = "./images/Zoo-Map.jpg" # size = 1025 x 1024

# -----------------------------------------------------------

st.title('Synthetic Zoo')

# Create two columns
col1, col2 = st.columns([1.7,1])

# Display the image with the point in Streamlit
#st.image(image, caption="Map with Point", use_column_width=True)

# Add an image to the first column
with col1:

    st.image(image_path,
             #width = 350,
             caption = 'Map of The Zoo',
             use_container_width="always")
    
    # st.markdown(hover_html, unsafe_allow_html=True)

# Add text to the second column
with col2:
    st.write("Here's a map of the Synthetic Zoo.")
    st.write("The image was created manually in Paint, from multiple images generated by prompting a DALL-E Diffusion model")
    st.write("The data that defines the Zoo was generated with the help of ChatGPT, AI accounted for ~55% of the work required")